Set up configuration and initialize connection to Kentix endpoints
eliona-smart-building-assistant/kentix-app pull request #3
Opened 2023-03-07 15:09 UTC by zdevaty

2023-03-08 07:07 UTC, andreas-goebel requested changes
for API access, please use our methods from go-utils/http

2023-03-08 07:07 UTC, andreas-goebel commented on kentix/kentix.go
>  	req, err := http.NewRequest("GET", url, nil)
For an API access, please use our methods from go-utils/http. At the moment there is no method for authorization Basic with an API-Key, but I will create such a method. The difference between the API mock and real Kentic devices is, that the devices needs an authorization. You can see that in https://dev.azure.com/eliona/apps/_git/kentix?path=/kentix_doorlock_get_data.sh

The methods for go-utils/http can you find here: https://github.com/eliona-smart-building-assistant/go-utils/tree/main/http

2023-03-08 07:07 UTC, andreas-goebel commented on kentix/kentix.go
>  	req, err := http.NewRequest("GET", url, nil)
There is already a method to do this:
http.NewRequestWithApiKey(url, "Authorization", "Basic " + API-Key from config in Base64)

2023-03-08 07:07 UTC, andreas-goebel commented on kentix/kentix.go
>  	req, err := http.NewRequest("GET", url, nil)
Pleae note, that the  API-Key from config from config have to encoded in Base64. See: https://dev.azure.com/eliona/apps/_git/kentix?path=/kentix_doorlock_get_data.sh

2023-03-08 07:07 UTC, andreas-goebel commented on kentix/kentix.go
>  	req, err := http.NewRequest("GET", url, nil)
With the method you can read the API in 2 lines:
request := http.NewRequestWithApiKey(url, "Authorization", "Basic " + conf.apiKey)
sensorData := http.Read[SensorData](request, 10, true)

2023-03-08 16:40 UTC, zdevaty commented on kentix/kentix.go
>  	req, err := http.NewRequest("GET", url, nil)
Thanks, I implemented it in the next CL.

2023-03-09 06:52 UTC, andreas-goebel approved these changes

2023-03-09 06:53 UTC, merged